export const CLEAR_DATA = 'CLEAR_DATA';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const ON_USER_SIGNUP = 'ON_USER_SIGNUP';
export const ON_USER_LOADED = 'ON_USER_LOADED';
export const ON_BUTTON_PRESSED = 'ON_BUTTON_PRESSED';
export const ON_ACTION_FAILED = 'ON_ACTION_FAILED';

export const ON_GAMES_LOADED = 'ON_GAMES_LOADED';
export const ON_HOUSES_LOADED = 'ON_HOUSES_LOADED';
export const ON_TEAMS_LOADED = 'ON_TEAMS_LOADED';
export const ON_MATCHES_LOADED = 'ON_MATCHES_LOADED';
export const ON_NEWS_LOADED = 'ON_NEWS_LOADED';
export const ON_RECENT_MATCHES_LOADED = 'ON_RECENT_MATCHES_LOADED';